# Generated by Django 2.2.2 on 2019-06-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_description', models.CharField(max_length=300)),
                ('post_created_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('NO', 'NONE'), ('LI', 'LIKE'), ('LO', 'LOVE'), ('HA', 'HAHA'), ('WO', 'WOW'), ('SA', 'SAD'), ('AN', 'ANGRY')], max_length=2)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Posts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_create_date', models.DateTimeField()),
                ('message', models.CharField(max_length=300)),
                ('commented_on_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Comments')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Posts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.User')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('NO', 'NONE'), ('LI', 'LIKE'), ('LO', 'LOVE'), ('HA', 'HAHA'), ('WO', 'WOW'), ('SA', 'SAD'), ('AN', 'ANGRY')], max_length=1)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Comments')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.User')),
            ],
        ),
    ]
