# Generated by Django 2.2.2 on 2019-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190626_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikes',
            name='reaction',
            field=models.CharField(choices=[('NO', 'NONE'), ('LI', 'LIKE'), ('LO', 'LOVE'), ('HA', 'HAHA'), ('WO', 'WOW'), ('SA', 'SAD'), ('AN', 'ANGRY')], max_length=2),
        ),
    ]
