# Generated by Django 2.2.2 on 2019-06-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
